

# CONSTANTS
#TESTS VERSION
    #TOKENS
TOKEN_LOCAL = "0123456789ABCDEF"
    #TEST AssistanceApps
AppID_LOCAL_ECHO_TEST = "LOCAL_ECHO_TEST"
AppID_SHA256_TEST = "SHA256_TEST"

#DEFAULT VALUES
#SYMBOLS
NOT_APPLYED = "NOT_APPLYED"
SYMBOL_OK = "ok"
#TIMES
TIME_SOCK_COOLDOWN = 0.0
#PORTS
PORT_API_REQUESTS = 21902
PORT_DATA_REQUESTS = 21962
PORT_FTP = 21982
#TYPES
TYPE_API_REQUEST_MSG = "MSG_API_REQUEST"
TYPE_API_REQUEST_ANS = "ANS_API_REQUEST"
TYPE_STATUS_CHECK_MSG = "MSG_STATUS_CHECK"
TYPE_STATUS_CHECK_ANS = "ANS_STATUS_CHECK"
TYPE_RECOVER_RESULTS_MSG = "MSG_RECOVER_RESULTS"
TYPE_RECOVER_RESULTS_ANS = "ANS_RECOVER_RESULTS"
TYPE_CHECKPOINT_MSG = "MSG_CHECKPOINT" #TODO the checkpoints are assistance requests sent by the app implementation!!!!
TYPE_CHECKPOINT_ANS = "ANS_CHECKPOINT" #TODO see line above
TYPE_DATA_SUBMIT_MSG = "MSG_DATA_SUBMIT"
TYPE_DATA_RECOVER_MSG = "MSG_DATA_RECOVER"
#CHANNELS
CHANNEL_IMMEDIATE = "IMMEDIATE"
CHANNEL_LOCAL_FILE = "LOCAL_FILE"
CHANNEL_FTP = "FTP"
#TASK STATUS
STATUS_DRAFT = "DRAFT"
STATUS_WAITING = "WAITING"
STATUS_PERFORMING_LOCAL = "PERFORMING_LOCAL"
STATUS_RECOVERING_DATA = "RECOVERING_DATA"
STATUS_COMPLETED_LOCAL = "COMPLETED_LOCAL"
STATUS_COMPLETED_REMOTE = "COMPLETED_REMOTE"
STATUS_INTERRUPTED_LOCAL = "INTERRUPTED_LOCAL"
STATUS_READY = "READY"
#DIRECTORIES
DIR_APPS_CWD = "AssistanceApps/"
DIR_LOGS = "LOG/"
#TUNNING
TUNNING_DEFAULT_PROCESS_PRIORITY = 10