#!/usr/bin/env python
'''
File that defines the Constants used in the Assistance System
Jose F. R. Fonseca
See Attached License file
'''
# CONSTANTS
# TESTS VERSION
# TOKENS
TOKEN_TESTS_VERSION = "0123456789ABCDEF"
# TEST AssistanceApps
AppID_LOCAL_ECHO_TEST = "LOCAL_ECHO_TEST"
AppID_SHA256_TEST = "SHA256_TEST"
AppID_SHA256_REMOTE_TEST = "SHA256_REMOTE_TEST"

# ACTUAL AssistanceApps
AppID_WEKA = "WEKA_3_6_12"

# DEFAULT VALUES
# SYMBOLS
NOT_APPLYED = "NOT_APPLYED"
SYMBOL_OK = "ok"
NULL = "0"
SYMBOL_SEPARATOR = "(||x||)"
# TIMES
TIME_SOCK_COOLDOWN = 0.0
TIME_DATA_SERVER_INTERVAL = 0.25
# PORTS
PORT_API_REQUESTS = 21902
PORT_DATA_REQUESTS = 21962
# TYPES
TYPE_API_REQUEST_MSG = "MSG_API_REQUEST"
TYPE_API_REQUEST_ANS = "ANS_API_REQUEST"
TYPE_STATUS_CHECK_MSG = "MSG_STATUS_CHECK"
TYPE_STATUS_CHECK_ANS = "ANS_STATUS_CHECK"
TYPE_RECOVER_RESULTS_MSG = "MSG_RECOVER_RESULTS"
TYPE_RECOVER_RESULTS_ANS = "ANS_RECOVER_RESULTS"
TYPE_CHECKPOINT_MSG = "MSG_CHECKPOINT" # #TODO the checkpoints are assistance requests sent by the app implementation!!!! @IgnorePep8
TYPE_CHECKPOINT_ANS = "ANS_CHECKPOINT" # #TODO see line above @IgnorePep8
TYPE_DATA_SUBMIT_MSG = "MSG_DATA_SUBMIT"
TYPE_DATA_RECOVER_MSG = "MSG_DATA_RECOVER"
# CHANNELS
CHANNEL_IMMEDIATE = "IMMEDIATE"
CHANNEL_LOCAL_FILE = "LOCAL_FILE"
CHANNEL_FTP = "FTP"
CHANNEL_ZIP_FTP = "ZIP_FTP"
# TASK STATUS
STATUS_DRAFT = "DRAFT"
STATUS_WAITING = "WAITING"
STATUS_REJECTED = "REJECTED"
STATUS_GATHERING_DATA = "GATHERING"
STATUS_DATA_READY = "DATA READY"
STATUS_SETTING_UP = "SETTING UP"
STATUS_STANDBY = "STANDBY"
STATUS_PERFORMING_LOCAL = "PERFORMING_LOCAL"
STATUS_COMPLETED_LOCAL = "COMPLETED_LOCAL"
STATUS_INTERRUPTED_LOCAL = "INTERRUPTED_LOCAL"
STATUS_READY = "READY"

STATUS_FINISHED = "FINISHED"


STATUS_RECOVERING_DATA = "RECOVERING_DATA"
STATUS_COMPLETED_REMOTE = "COMPLETED_REMOTE"
STATUS_SENDING_DATA = "SENDING_DATA"
# DIRECTORIES
DIR_RUNTIME_IO = "runtimeIO/"
DIR_APPS_CWD = "AssistanceApps/"+DIR_RUNTIME_IO
DIR_LOGS = "LOG/"
# TUNNING
TUNNING_DEFAULT_PROCESS_PRIORITY = 10
